### ISSUE TITLE
Domain expiring

### ISSUE THREAD

**Issue by jden** [codeforamerica/bestnest-app#125]
The domain bestnestapp.com is registered in my name. It's expiring on 2016-06-16, and I don't intend to renew it. If CfA is interested in taking it over, I'm happy to transfer it or do whatever else is necessary on my end.

/cc @migurski @ondrae

**Comment by jden** [comment]
The domain has expired. I'm going to close this issue.

**Comment by jeremiak** [comment]
RIP BN :pray:

**Comment by jden** [comment]
:chart_with_upwards_trend: onward and upward, I say!
